language: android

android:
  components:
    - platform-tools
    - tools
    - android-22
    - extra-android-m2repository
    - build-tools-22.0.1

branches:
  only:
    - master

script:
    - ./gradlew clean assembleRelease

notifications:
  email: false